### ISSUE TITLE
You got mentioned in CHANGLEOG's newsletter

### ISSUE THREAD

**Issue by DjebbZ** [seancorfield/readme#2]
https://changelog.com/news/a-testing-library-that-turns-your-readme-into-executable-tests-83WZ?utm_medium=email&utm_campaign=Weekly%20-%20Issue%20296&utm_content=Weekly%20-%20Issue%20296+CID_4741e0aa19952749273b1aad24e9db8b&utm_source=changelog%20email&utm_term=Discuss

**Comment by seancorfield** [comment]
Cool. Thanks for the heads up!
