### ISSUE TITLE
Add an explanation of how to run via leiningen

### ISSUE THREAD

**Issue by Akeboshiwind** [seancorfield/readme#5]
Hi, I was thinking it would be useful to add an explanation of how to use this library with lein. I know it confused me for a bit 🙂.

It's as simple as a user adding the following to their profile.clj:
```clojure
{:profiles {:doc-test {:dependencies [[seancorfield/readme "1.0.13"]]
                       :aliases {"doc-test" ["run" "-m" "seancorfield.readme"]}}}}
```

Then the following can be used to run the tests:
```bash
lein with-profile doc-test doc-test
```

**Comment by seancorfield** [comment]
I haven't used Leiningen for so long that I didn't even think about instructions for it! Thank you! I'll give this a quick test and then update the README.
